### ISSUE TITLE
Perhaps changing the license to a more permissive one?

### ISSUE THREAD

**Issue by MohammedKHC0** [haodong404/codroid#1]
I have seen this project and it looks really good, I really like that it's written entirely on Kotlin, and I would like to use editor module on my application, but my application is not GPL compatible. So I was just asking if you could consider changing the license to a more permissive one (ex Apache 2.0, MIT, EPL.. etc)

I completely understand that this is your code and effort, you are free to license it under what you want.
Have a nice day, I hope to see your project growing up!

**Comment by haodong404** [comment]
Thank you for your attention to this toy project. I'm glad to changing the license to MIT, as I no long have the time to maintain it. https://github.com/haodong404/codroid/commit/c59f5350d1cf75fd078cd7de4905908f8b012672

**Comment by MohammedKHC** [comment]
Thanks is to you, thank you so much for changing the license. And it's not a toy project. It's really great.

Also i made a PR that removes GPL license header from source files. can you review it?
#2
